import { defaultBrand, type Brand } from '../brands';
import { breakpoint } from '../primitive';
import {
  desktopBreakpoint,
  flatten,
  resolve,
  type Mode,
  type SemanticPath,
  type SemanticTokens,
} from '../semantic';

const unitless = new Set(['fontWeight', 'zIndex']);
const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

/** 'color.bg.secondary' → '--brt-color-bg-secondary' */
export function cssVarName(path: SemanticPath | string): string {
  return `--brt-${path.split('.').map(kebab).join('-')}`;
}

export function cssValue(path: string, value: string | number): string {
  if (typeof value === 'string') return value;
  const group = path.split('.')[0] ?? '';
  return unitless.has(group) ? String(value) : `${value}px`;
}

// token ที่ขึ้นกับ brand — ไฟล์ CSS ของ brand มีเฉพาะกลุ่มนี้
const brandGroups = new Set(['color', 'font']);

function declarations(tokens: SemanticTokens, filter: (path: string) => boolean) {
  return flatten(tokens)
    .filter(([path]) => filter(path))
    .map(([path, value]) => `  ${cssVarName(path)}: ${cssValue(path, value)};`)
    .join('\n');
}

/**
 * tokens.css — token ทุกตัวของ `defaultBrand` ที่ `:root`
 * mobile-first: ค่าเริ่มต้นเป็น mobile แล้ว override ค่า desktop ตั้งแต่ breakpoint `desktopBreakpoint`
 */
export function generateTokensCss(): string {
  const mobile = resolve(defaultBrand, 'light', 'mobile');
  const mobileValues = new Map(flatten(mobile));
  const changed = flatten(resolve(defaultBrand, 'light', 'desktop'))
    .filter(([path, value]) => mobileValues.get(path) !== value)
    .map(([path, value]) => `    ${cssVarName(path)}: ${cssValue(path, value)};`)
    .join('\n');

  return (
    [
      '/* generated by @brt-innovation/design — ห้ามแก้ด้วยมือ */',
      `:root {\n${declarations(mobile, () => true)}\n}`,
      `@media (min-width: ${breakpoint[desktopBreakpoint]}px) {\n  :root {\n${changed}\n  }\n}`,
    ].join('\n\n') + '\n'
  );
}

export interface BrandCssOptions {
  /** ค่าเริ่มต้น `:root[data-brand='<name>']` — ชนะ `:root` ของ tokens.css เสมอไม่ว่าลำดับไฟล์ */
  selector?: string;
  mode?: Mode;
}

/**
 * CSS ของ brand ที่โปรเจกต์ประกาศเอง — override เฉพาะ token ที่ขึ้นกับ brand (สี, ฟอนต์)
 * ใช้คู่กับ tokens.css (มาจาก adapter อยู่แล้ว) แล้วใส่ `data-brand="<name>"` ที่ `<html>`
 */
export function generateBrandCss(brand: Brand, options: BrandCssOptions = {}): string {
  const selector = options.selector ?? `:root[data-brand='${brand.name}']`;
  const tokens = resolve(brand, options.mode ?? 'light');
  return `${selector} {\n${declarations(tokens, (path) => brandGroups.has(path.split('.')[0] ?? ''))}\n}\n`;
}

type Vars<T> = { [K in keyof T]: T[K] extends string | number ? string : Vars<T[K]> };
export type BrtVars = Vars<SemanticTokens>;

/** โครงเดียวกับ semantic token แต่ค่าเป็น 'var(--...)' — สำหรับ CSS-in-JS */
export function createVars(): BrtVars {
  const build = (obj: object, prefix: string): object =>
    Object.fromEntries(
      Object.entries(obj).map(([k, v]) => {
        const path = prefix ? `${prefix}.${k}` : k;
        return [
          k,
          typeof v === 'object' && v !== null ? build(v, path) : `var(${cssVarName(path)})`,
        ];
      }),
    );
  return build(resolve(), '') as BrtVars;
}

/** `vars.color.text.primary` → `'var(--brt-color-text-primary)'` */
export const vars: BrtVars = createVars();
