import { brands, defaultBrand, type BrandName } from '../brands';
import { breakpoint } from '../primitive';
import {
  desktopBreakpoint,
  flatten,
  modes,
  resolve,
  type Mode,
  type SemanticPath,
  type SemanticTokens,
} from '../semantic';

const unitless = new Set(['fontWeight', 'zIndex']);
const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

/** 'color.bg.secondary' → '--brt-color-bg-secondary' */
export function cssVarName(path: SemanticPath | string): string {
  return `--brt-${path.split('.').map(kebab).join('-')}`;
}

export function cssValue(path: string, value: string | number): string {
  if (typeof value === 'string') return value;
  const group = path.split('.')[0] ?? '';
  return unitless.has(group) ? String(value) : `${value}px`;
}

// token ที่ต่างกันตาม brand / mode — selector ของ brand/mode ใส่เฉพาะกลุ่มนี้
const themed = new Set(['color', 'font']);

function block(selector: string, tokens: SemanticTokens, onlyThemed: boolean): string {
  const lines = flatten(tokens)
    .filter(([path]) => !onlyThemed || themed.has(path.split('.')[0] ?? ''))
    .map(([path, value]) => `  ${cssVarName(path)}: ${cssValue(path, value)};`);
  return `${selector} {\n${lines.join('\n')}\n}`;
}

function selectorFor(brand: BrandName, mode: Mode): string {
  const isDefault = brand === defaultBrand;
  if (mode === 'light')
    return isDefault ? `:root,\n[data-brand='${brand}']` : `[data-brand='${brand}']`;
  return isDefault
    ? `[data-mode='dark'],\n[data-brand='${brand}'][data-mode='dark']`
    : `[data-brand='${brand}'][data-mode='dark']`;
}

/** token ที่ค่า desktop ต่างจาก mobile (typography, radius) — ใช้ร่วมทุก brand */
function desktopBlock(): string {
  const mobile = new Map(flatten(resolve(defaultBrand, 'light', 'mobile')));
  const lines = flatten(resolve(defaultBrand, 'light', 'desktop'))
    .filter(([path, value]) => mobile.get(path) !== value)
    .map(([path, value]) => `    ${cssVarName(path)}: ${cssValue(path, value)};`);
  return `@media (min-width: ${breakpoint[desktopBreakpoint]}px) {\n  :root {\n${lines.join('\n')}\n  }\n}`;
}

/**
 * tokens.css — ทุก brand × mode ในไฟล์เดียว เลือกด้วย data-brand / data-mode ที่ <html>
 * ค่าเริ่มต้นเป็น mobile แล้ว override เป็น desktop ตั้งแต่ breakpoint `desktopBreakpoint`
 */
export function generateTokensCss(): string {
  const parts = ['/* generated by @brt/design — ห้ามแก้ด้วยมือ */'];
  for (const brand of Object.keys(brands) as BrandName[]) {
    for (const mode of modes) {
      const isRoot = brand === defaultBrand && mode === 'light';
      parts.push(block(selectorFor(brand, mode), resolve(brand, mode), !isRoot));
    }
  }
  parts.push(desktopBlock());
  return parts.join('\n\n') + '\n';
}

type Vars<T> = { [K in keyof T]: T[K] extends string | number ? string : Vars<T[K]> };
export type BrtVars = Vars<SemanticTokens>;

/** โครงเดียวกับ semantic token แต่ค่าเป็น 'var(--brt-...)' — สำหรับ CSS-in-JS */
export function createVars(): BrtVars {
  const build = (obj: object, prefix: string): object =>
    Object.fromEntries(
      Object.entries(obj).map(([k, v]) => {
        const path = prefix ? `${prefix}.${k}` : k;
        return [
          k,
          typeof v === 'object' && v !== null ? build(v, path) : `var(${cssVarName(path)})`,
        ];
      }),
    );
  return build(resolve(defaultBrand, 'light'), '') as BrtVars;
}
