import { copyFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import {
  cssValue,
  cssVarName,
  defaultBrand,
  flatten,
  resolve,
  type SemanticPath,
} from '@brt/design';
import { tailwindTheme } from '../src/mapping';

const dist = new URL('../dist/', import.meta.url);
mkdirSync(dist, { recursive: true });

// tokens.css (ทุก brand × mode) มาจาก @brt/design
const require = createRequire(import.meta.url);
copyFileSync(require.resolve('@brt/design/tokens.css'), new URL('tokens.css', dist));

const tokens = flatten(resolve(defaultBrand, 'light'));
const themed: string[] = [];
const literal: string[] = [];
const utilities: string[] = [];

for (const [path, value] of tokens) {
  const target = tailwindTheme[path as SemanticPath];
  if (path.startsWith('zIndex.')) {
    utilities.push(`@utility z-${path.split('.')[1]} {\n  z-index: var(${cssVarName(path)});\n}`);
  } else if (path.startsWith('breakpoint.')) {
    literal.push(`  ${target}: ${Number(value) / 16}rem;`);
  } else if (target) {
    themed.push(`  ${target}: var(${cssVarName(path)});`);
  }
}

const css = `/* generated by @brt/tailwind — ห้ามแก้ด้วยมือ */
@import './tokens.css';

/* ปิดค่า default ของ Tailwind ในหมวดที่ BRT กำหนดเอง — กันการใช้ bg-blue-500, rounded-3xl ฯลฯ ที่ไม่ใช่ token */
@theme {
  --color-*: initial;
  --text-color-*: initial;
  --background-color-*: initial;
  --border-color-*: initial;
  --font-*: initial;
  --text-*: initial;
  --font-weight-*: initial;
  --leading-*: initial;
  --tracking-*: initial;
  --radius-*: initial;
  --shadow-*: initial;
  --breakpoint-*: initial;
  /* spacing ของ Figma ตั้งชื่อเป็น px (Space/8 = 8px) — ให้ตัวเลขของ Tailwind เป็น px ด้วย: p-8 = 8px, h-40 = 40px */
  --spacing: 1px;
${literal.join('\n')}
}

/* อ้าง var(--brt-*) จึงสลับตาม data-brand / data-mode ได้ */
@theme inline {
  --color-transparent: transparent;
  --color-current: currentColor;
  --color-white: #fff;
  --color-black: #000;
${themed.join('\n')}
}

${utilities.join('\n\n')}
`;

writeFileSync(new URL('theme.css', dist), css);
console.log('@brt/tailwind: dist/theme.css, dist/tokens.css');
